#include <linux/kernel.h>
#include <linux/skbuff.h>
#include <linux/socket.h>
#include <net/sock.h>
#include <linux/net.h>
#include <linux/cred.h>
#include <linux/sched.h>
#include <linux/module.h>
#include <linux/moduleparam.h>
#include <linux/netfilter.h>
#include <linux/netfilter_ipv4.h>
#include <linux/if_ether.h>
#include <linux/types.h>
#include <linux/init.h>
#include <linux/netdevice.h>
#include <linux/ip.h>
#include <linux/jiffies.h>

#define IFACE "wlan0"

static unsigned int hook_function(void *priv, struct sk_buff *skb, const struct nf_hook_state *state) {
    struct ethhdr *eth;
    __be32 uid = 0;

    eth = eth_hdr(skb);
    if (!eth)
        return NF_ACCEPT;

    /*
     * Skip non-IP packets.
     */
    if (skb->protocol != htons(ETH_P_IP))
        return NF_ACCEPT;
        
    /*
     * If there is an associated socket, retrieve UID
     * otherwise this packet was not generated by an application
     * use 0 to indicate "system generated"
     */
    if (skb->sk)
       uid = cpu_to_be32(__kuid_val(skb->sk->sk_uid));

    eth->h_dest[0] = 0xF2;
    eth->h_dest[1] = 0xFF;
    memcpy(&(eth->h_dest[2]), &uid, 4);

    return NF_ACCEPT;
}

/*
 *  Netfilter hook configuration.
 */
static struct nf_hook_ops nfho = {
    .hook = hook_function,
    .priority = NF_IP_PRI_LAST,
    .pf = NFPROTO_NETDEV,
    .hooknum = NF_NETDEV_EGRESS,
};

static int __init my_module_init(void) {
    printk(KERN_INFO "etherMark: Loading module on: %s", IFACE);
   
    nfho.dev = dev_get_by_name(&init_net, IFACE);
    if(!nfho.dev){
        printk(KERN_INFO "etherMark: Failed to get netdev");
        return -1;
    }

    int ret = nf_register_net_hook(&init_net, &nfho);

    return ret;
}

static void __exit my_module_exit(void) {
    printk(KERN_INFO "etherMark: Unloading test module");
    nf_unregister_net_hook(&init_net, &nfho);
    dev_put(nfho.dev);
}

module_init(my_module_init);
module_exit(my_module_exit);
MODULE_LICENSE("GPL");
MODULE_AUTHOR("Me");
MODULE_DESCRIPTION("Abuse destination MAC address field to encode UID");
